import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Nav from './components/Nav';

export const metadata: Metadata = {
	title: 'Skin & Sage',
	description: 'Generated by create next app',
	robots: 'index, follow',
};

const Gothic = localFont({
	src: '../../public/fonts/CenturyGothic.ttf',
});

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={`${Gothic.className} antialiased`}>
				<Nav />
				{children}
			</body>
		</html>
	);
}
